add --force-version-override

diff --git a/dkms b/dkms
--- a/dkms
+++ b/dkms
@@ -136,7 +136,7 @@ show_usage()
     echo $"  [action]  = { add | remove | build | install | uninstall | match | autoinstall | mkdriverdisk |"
     echo $"                mktarball | ldtarball | mkrpm | mkkmp | mkdeb | mkdsc | mkbmdeb | status }"
     echo $"  [options] = [-m module] [-v module-version] [-k kernel-version] [-a arch]"
-    echo $"              [-d distro] [-c dkms.conf-location] [-q] [--force] [--all]"
+    echo $"              [-d distro] [-c dkms.conf-location] [-q] [--force] [--force-version-override] [--all]"
     echo $"              [--templatekernel=kernel] [--directive='cli-directive=cli-value']"
     echo $"              [--config=kernel-.config-location] [--archive=tarball-location]"
     echo $"              [--kernelsourcedir=source-location] [--no-prepare-kernel] [--no-initrd]"
@@ -815,35 +815,37 @@ check_version_sanity()
     read -a kernels_module < <(find_module "$lib_tree" "${4}")
     [ -z $kernels_module ] && return 0
 
-    if [[ ${kernels_module[1]} ]]; then
-        warn $"Warning! Cannot do version sanity checking because multiple ${4}$module_suffix" \
-            $"modules were found in kernel $1."
-        return 0
-    fi
-    local dkms_module=$(compressed_or_uncompressed "$dkms_tree/$module/$module_version/$1/$2/module/" "${4}")
-    get_module_verinfo $kernels_module; kernels_info=("${res[@]}")
-    get_module_verinfo $dkms_module; dkms_info=("${res[@]}")
-    if [[ ! ${dkms_info[1]} && ${kernels_info[1]} ]]; then
-        # Use obsolete checksum info
-        dkms_info[1]=${dkms_info[2]}
-        kernels_info[1]=${kernels_info[2]}
-    fi
-
-    if [[ ${kernels_info[1]} && ${dkms_info[1]} && ${kernels_info[1]} = ${dkms_info[1]} &&
-	  -n "${kernels_info[0]}" && -n "${dkms_info[0]}" && ${kernels_info[0]} = ${dkms_info[0]} && ! $force ]]; then
-        echo $"" >&2
-        echo $"Good news! Module version $dkms_info for ${4}$module_suffix" >&2
-        echo $"exactly matches what is already found in kernel $1." >&2
-        echo $"DKMS will not replace this module." >&2
-        echo $"You may override by specifying --force." >&2
-        return 1
-    fi
-
-    if [[ $kernels_info && $dkms_info && ! ( $(VER $dkms_info) > $(VER $kernels_info) ) && ! $force ]]; then
-        error $"Module version $dkms_info for ${4}$module_suffix" \
-            $"is not newer than what is already found in kernel $1 ($kernels_info)." \
-            $"You may override by specifying --force."
-        return 1
+    if [[ ! $force_version_override ]]; then
+        if [[ ${kernels_module[1]} ]]; then
+            warn $"Warning! Cannot do version sanity checking because multiple ${4}$module_suffix" \
+                $"modules were found in kernel $1."
+            return 0
+        fi
+        local dkms_module=$(compressed_or_uncompressed "$dkms_tree/$module/$module_version/$1/$2/module/" "${4}")
+        get_module_verinfo $kernels_module; kernels_info=("${res[@]}")
+        get_module_verinfo $dkms_module; dkms_info=("${res[@]}")
+        if [[ ! ${dkms_info[1]} && ${kernels_info[1]} ]]; then
+            # Use obsolete checksum info
+            dkms_info[1]=${dkms_info[2]}
+            kernels_info[1]=${kernels_info[2]}
+        fi
+    
+        if [[ ${kernels_info[1]} && ${dkms_info[1]} && ${kernels_info[1]} = ${dkms_info[1]} &&
+    	  -n "${kernels_info[0]}" && -n "${dkms_info[0]}" && ${kernels_info[0]} = ${dkms_info[0]} && ! $force ]]; then
+            echo $"" >&2
+            echo $"Good news! Module version $dkms_info for ${4}$module_suffix" >&2
+            echo $"exactly matches what is already found in kernel $1." >&2
+            echo $"DKMS will not replace this module." >&2
+            echo $"You may override by specifying --force." >&2
+            return 1
+        fi
+    
+        if [[ $kernels_info && $dkms_info && ! ( $(VER $dkms_info) > $(VER $kernels_info) ) && ! $force ]]; then
+            error $"Module version $dkms_info for ${4}$module_suffix" \
+                $"is not newer than what is already found in kernel $1 ($kernels_info)." \
+                $"You may override by specifying --force."
+            return 1
+        fi
     fi
 
     return 0
@@ -3662,6 +3664,9 @@ while (($# > 0)); do
             ;;
         --force)
             force="true"
+            ;;
+        --force-version-override)
+            force_version_override="true"
             ;;
         --all)
             all="true"
